export type Section = { title: string; items: string[] };
export type Phase = { id: string; title: string; blurb: string; sections: Section[] };

export const overview: [string, string][] = [
  ['Duration', '24 hours'],
  ['Mode', 'Offline, on-campus'],
  ['Date', 'End of October (tentative)'],
  ['Scale', 'National'],
  ['Teams', '75–100 teams × 4 members'],
  ['Eligibility', 'Inter-college; no gender requirement'],
  ['Registration', 'Unstop'],
  ['Format', 'Round 1 PPT screening → Round 2 24-hr hackathon'],
  ['Judging', '3 rounds'],
  ['Food & Stay', 'Provided by organisers'],
];

export const phases: Phase[] = [
  {
    id: 'pre',
    title: 'Pre-Event Planning',
    blurb: 'Everything to lock before participants arrive.',
    sections: [
      {
        title: 'Permissions & Legal',
        items: [
          'College management approval',
          'Venue booking confirmation',
          'Overnight stay permission',
          'Police / local authority permission (if required)',
          'Fire & safety clearance',
          'Electricity load approval',
          'Food vendor licence check (FSSAI)',
          'Participant undertaking / liability waiver',
          'Photo & video consent clause',
          'Terms & Conditions',
          'Code of Conduct & anti-harassment policy',
          'IP ownership & open-source rules',
          'Sponsor agreements / MoUs signed',
        ],
      },
      {
        title: 'Sponsorship',
        items: [
          'Sponsorship deck & brochure',
          'Tiered packages (Title, Powered-by, Associate)',
          'Sponsor deliverables sheet (logo, stall, stage mention, PS, workshop, hiring access)',
          'Banks & large companies outreach',
          'Cloud partner',
          'Banking / fintech partner',
          'Blockchain partner',
          'Healthcare partner',
          'Logistics partner',
          'Energy drink partners (Red Bull / Monster)',
          'Training / ed-tech partners',
          'Food & beverage partner',
          'Media partner',
          'Merchandise & printing partner',
          'Cloud credits & API keys from partners',
          'Stall sales for extra revenue',
          'Sponsor logo deadline for prints',
        ],
      },
      {
        title: 'Registration & Participants',
        items: [
          'Unstop event listing',
          'Registration form (team of 4, inter-college)',
          'Team size validation',
          'College ID verification',
          'No-show / member replacement policy',
          'Shortlist / waitlist / rejection emails',
          'Confirmation & RSVP from shortlisted teams',
          'Participant database',
          'Emergency contact collection',
          'Dietary preferences collection',
          'T-shirt size collection',
          'Travel & arrival instructions to teams',
          'Official event email ID & templates',
        ],
      },
      {
        title: 'Problem Statements',
        items: [
          'Domain-wise PS drafting (cloud, banking, blockchain, healthcare, logistics)',
          'Sponsor PS lock-in deadline',
          'Open innovation track',
          'Difficulty balancing',
          'PS owner / mentor for each statement',
          'Expected deliverables per PS',
          'Datasets & APIs availability',
          'PS document formatted for release',
        ],
      },
      {
        title: 'Judges & Mentors',
        items: [
          'Judge outreach & approach',
          'Judge confirmation',
          'Conflict-of-interest policy',
          'Judging rubric & score sheets',
          'Judge briefing document',
          'Judge travel & accommodation',
          'Judge pickup plan',
          'Mentor recruitment by domain',
          'Mentor overnight shifts',
          'Faculty / teacher support roster',
        ],
      },
      {
        title: 'Marketing & PR',
        items: [
          'Event website (schedule, PS, sponsors, FAQ)',
          'Poster design',
          'Poster & banner prints',
          'Reels & posts promotion',
          'Instagram campaign',
          'LinkedIn campaign',
          'WhatsApp / Telegram / Discord community',
          'Visiting nearby colleges',
          'College ambassador program',
          'Email campaign to colleges',
          'Tech communities & hackathon listing sites',
          'Countdown & sponsor announcement posts',
          'Press release / local media',
          'Stall promotion to vendors',
        ],
      },
      {
        title: 'Venue & Infrastructure',
        items: [
          'Venue layout plan',
          'Coding hall for 300–400 participants',
          'Tables & chairs',
          'Registration desk',
          'Bag / locker room',
          'Judge room',
          'Mentor desk',
          'Stall area',
          'Food / dining area',
          'Sleeping area',
          'Medical / first-aid room',
          'Control room for core team',
          'Washroom readiness',
          'Stage, mic, speakers & projector',
          'Decoration & banners plan',
          'Photo booth design',
        ],
      },
      {
        title: 'Tech & Power',
        items: [
          'Wi-Fi capacity test (400+ devices)',
          'Backup internet / hotspots',
          'Extension boards (min. 1 per team)',
          'Power backup / generator',
          'Charging stations',
          'Submission portal',
          'Backup submission method',
          'Participant starter-kit doc (Wi-Fi, GitHub, credits, rules)',
          'Food token & participant management app',
          'App offline / paper fallback',
        ],
      },
      {
        title: 'Food & Stay',
        items: [
          'Caterer booking',
          'Tent house booking',
          'Meal count with 10% buffer',
          'Veg / non-veg / Jain options',
          'Water stations',
          '24-hour tea & coffee',
          'Mattresses / sleeping mats',
          'Blankets & pillows',
          'Separate sleeping areas',
          'Washroom cleaning schedule',
        ],
      },
      {
        title: 'Kits, Printing & Merch',
        items: [
          'ID card order',
          'Badges & lanyards',
          'Welcome kit contents',
          'T-shirts',
          'Goodies & swag',
          'Standees & banners',
          'Certificate design',
          'Certificate printing',
          'Trophies & mementos',
          'Mystery box items',
        ],
      },
      {
        title: 'Safety & Security',
        items: [
          'Security guards (day & night shifts)',
          'Entry / exit control',
          'Wristbands / ID checks',
          'CCTV coverage',
          'Fire extinguishers & emergency exits',
          'First-aid kit',
          'Doctor on call & ambulance tie-up',
          "Women's safety & support desk",
          'Emergency lead designated',
          'Evacuation plan',
          'Incident reporting process',
        ],
      },
      {
        title: 'Team & Volunteers',
        items: [
          'Core leads (Event, Ops, Sponsorship, Tech, PR, Finance)',
          'Volunteer recruitment',
          'Duty roster with shifts',
          'Volunteer briefing & training',
          'Volunteer T-shirts & IDs',
          'Team managers assigned to participant teams',
          'Master operations sheet (task, owner, deadline, status)',
        ],
      },
      {
        title: 'Budget & Finance',
        items: [
          'Budget sheet',
          'Sponsorship revenue tracking',
          'Stall fee collection',
          'Registration fee decision',
          'Expense heads (food, venue, printing, kits, prizes, stay, security, AV)',
          '10–15% contingency',
          'Payment approvals & reimbursements',
          'Receipts & invoices file',
        ],
      },
    ],
  },
  {
    id: 'mid',
    title: 'Mid-Event · 24 Hours',
    blurb: 'Running the floor from check-in to final submission.',
    sections: [
      {
        title: 'Opening & Check-in',
        items: [
          'Participant check-in (QR)',
          'ID verification',
          'Consent letters collected',
          'Welcome kit distribution',
          'Bag / locker room handover',
          'Seating allocation',
          'Wi-Fi credentials shared',
          'Rangoli & decoration',
          'Saraswati pujan / lamp lighting',
          'Inauguration ceremony',
          'Rules & code-of-conduct briefing',
          'Emergency & safety briefing',
          'Problem statement distribution',
          'Sponsor & mentor introductions',
          'Hacking start announcement',
        ],
      },
      {
        title: 'Food & Refreshments',
        items: [
          'Lunch (Day 1)',
          'Dinner (Day 1)',
          'Midnight snacks',
          'Breakfast (Day 2)',
          'Tea & snack rounds',
          'Energy drinks (Red Bull / Monster)',
          'Food token redemption at counters',
          "Judges' food",
          'Water refills',
        ],
      },
      {
        title: 'Hackathon Operations',
        items: [
          'Mentor rounds',
          'Tech help desk',
          'Wi-Fi & power support',
          'Announcements & schedule updates',
          'Participant help desk',
          'Night headcount',
          'Sleeping area supervision',
          'Washroom cleaning rounds',
          'Submission deadline reminders',
        ],
      },
      {
        title: 'Engagement',
        items: [
          'Jamming session',
          'Mind-refreshing mini games',
          'Midnight activity',
          'Photo booth',
          'Sponsor stalls & activities',
          'Stall management',
          'Workshops / tech talks',
          'Stretch break',
          'Sponsor giveaways',
          'Snack / candy jars',
        ],
      },
      {
        title: 'Judges & Guests',
        items: ['Judges pickup', 'Judge room & refreshments', 'Guest reception'],
      },
      {
        title: 'Safety',
        items: [
          'Security rounds overnight',
          'Medical desk staffed 24h',
          'Emergency contacts displayed',
          'Lost & found desk',
        ],
      },
    ],
  },
  {
    id: 'judging',
    title: 'Judging & Awards',
    blurb: 'PPT screening, the 3 on-campus rounds, and prizes.',
    sections: [
      {
        title: 'Round 1 · PPT Screening',
        items: [
          'PPT template published',
          'Submission deadline',
          'Judge allocation',
          'Screening rubric',
          'Conflict-of-interest check',
          'Shortlisting',
          'Results communicated',
        ],
      },
      {
        title: 'On-campus Evaluations',
        items: [
          'Evaluation 1 · 6 PM (idea validation)',
          'Evaluation 2 · overnight (progress check)',
          'Evaluation 3 · 10 AM (final)',
          'Judge schedule per room',
          'Score sheet collection',
          'Mentor feedback notes',
        ],
      },
      {
        title: 'Final Judging & Demo',
        items: [
          'Demo schedule & time slots',
          'Presentation timer',
          'Backup laptop & projector',
          'Demo-failure policy',
          'Tie-breaker rules',
          'Score consolidation',
          'Result verification & sign-off',
        ],
      },
      {
        title: 'Prizes & Certificates',
        items: [
          'Prize categories (top 3, domain, best UI/UX, innovation, sponsor tech)',
          'Prize check before ceremony',
          'Winner eligibility verification',
          'Winner bank details',
          'Cash prize transfer process',
          'Trophies & medals',
          'Participation certificates',
          'Winner certificates',
          'Announcement script',
        ],
      },
    ],
  },
  {
    id: 'post',
    title: 'Post-Event',
    blurb: 'Closing, wrap-up, content and follow-ups.',
    sections: [
      {
        title: 'Closing Ceremony',
        items: [
          'Speech',
          'Flowers & bouquets',
          'Felicitation of guests, judges & sponsors',
          'Prize distribution',
          'Certificate distribution',
          'Mystery box',
          'Group photo',
        ],
      },
      {
        title: 'Hospitality',
        items: ['Team lunch with special guests', 'Judges drop-off', 'Sponsor send-off'],
      },
      {
        title: 'Wrap-up',
        items: [
          'Sponsor stall cleanup & security',
          'Venue cleanup',
          'Returning all borrowed things',
          'Tent house & AV return',
          'First-aid kit restock',
          'Lost & found handover',
          'Vendor payments & finance settlement',
        ],
      },
      {
        title: 'Media & Content',
        items: [
          'Event video / aftermovie',
          'Reel shoot',
          'Photo album',
          'Social media recap',
          'LinkedIn post',
          'Winner interviews & testimonials',
          'Sponsor & marketing thank-you posts',
          'Press release',
        ],
      },
      {
        title: 'Showcase & Follow-up',
        items: [
          'Winner project showcase page',
          'GitHub / project archive',
          'E-certificates delivery',
          'Participant feedback form',
          'Judge & sponsor feedback',
          'Prize payout tracking',
          'Sponsor report (reach, footfall, deliverables)',
          'Final event report',
        ],
      },
    ],
  },
];
